
name: "junit-jupiter macos Building Java Applications CI workflow"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month

jobs:

     

  junit-jupiter-kotlin-java-gradle-macos-latest:
    name: "Building Java Applications Sample Kotlin junit-jupiter"
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "Building Java Applications Sample Kotlin junit-jupiter"
      run: |
          mkdir demo && cd demo
          # gradle init --project-name demo --type java-application --dsl kotlin
          gradle init --project-name demo --type java-application --dsl kotlin --test-framework junit-jupiter
          # gradle init --project-name demo --type java-application --dsl kotlin --test-framework spock
          # gradle init --project-name demo --type java-application --dsl kotlin --test-framework testng
          echo "==================Run the application=================================================================="   
          ./gradlew run        
          echo "==================Bundle the application=================================================================="              
          ./gradlew build 
          echo "==================Publish a Build Scan=================================================================="              
          ./gradlew build --scan
          cat app/build.gradle.kts          

  junit-jupiter-kotlin-java-gradle-macos-11:
    name: "Building Java Applications Sample Kotlin junit-jupiter"
    runs-on: macos-11
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "Building Java Applications Sample Kotlin junit-jupiter"
      run: |
          mkdir demo && cd demo
          # gradle init --project-name demo --type java-application --dsl kotlin
          gradle init --project-name demo --type java-application --dsl kotlin --test-framework junit-jupiter
          # gradle init --project-name demo --type java-application --dsl kotlin --test-framework junit-jupiter
          # gradle init --project-name demo --type java-application --dsl kotlin --test-framework testng
          echo "==================Run the application=================================================================="   
          ./gradlew run        
          echo "==================Bundle the application=================================================================="              
          ./gradlew build 
          echo "==================Publish a Build Scan=================================================================="              
          ./gradlew build --scan
          cat app/build.gradle.kts    

  junit-jupiter-kotlin-java-gradle-macos-1015:
    name: "Building Java Applications Sample Kotlin junit-jupiter"
    runs-on: macos-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "Building Java Applications Sample Kotlin junit-jupiter"
      run: |
          mkdir demo && cd demo
          # gradle init --project-name demo --type java-application --dsl kotlin
          gradle init --project-name demo --type java-application --dsl kotlin --test-framework junit-jupiter
          # gradle init --project-name demo --type java-application --dsl kotlin --test-framework spock
          # gradle init --project-name demo --type java-application --dsl kotlin --test-framework testng
          echo "==================Run the application=================================================================="   
          ./gradlew run        
          echo "==================Bundle the application=================================================================="              
          ./gradlew build 
          echo "==================Publish a Build Scan=================================================================="              
          ./gradlew build --scan
          cat app/build.gradle.kts            